on:
  push: {}

permissions:
  id-token: write # needed for configure-aws-credentials
  contents: read

jobs:
  opentofu-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::689053117832:role/github-oidc-provider-aws

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu Init
        id: init
        run: tofu init -input=false

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color
